# Site settings
title: Emi Marina
email: emimarinastudio@gmail.com
description: "Hand-carved jewelry in solid sterling silver. Embracing the beauty of imperfection with intentional distressing and maker's marks."
baseurl: ""
url: "https://www.emimarina.com"
api_key: YmYxYWVjMTktOWE2OC00Yjg0LThmNDYtY2RjMDQyMWMwMTk5NjM2MzQ5NzM3NzU3NzA3NjMw

# Collections
collections:
  products:
    output: true

values:
  layout: product
  permalink: "/products/:title"

# Google Analytics
googletagmanager: "UA-110956704-1"

# Team names, titles and social links

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://instagram.com/emimarinajewelry/
  - title: facebook
    url:  https://facebook.com/emimarinajewelry/
  # - title: twitter
    # url: http://twitter.com/
  # - title:  pinterest
    # url:  http://pinterest.com

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Jacksonville, FL

# Build settings
markdown: kramdown
permalink: pretty